/**
 * Bundled fallback data.
 *
 * Only ever used when the API is unreachable, and the UI shows an explicit
 * "showing offline sample data" banner whenever it is in play. Shapes mirror
 * `server/src/store/mockDb.js` exactly, so swapping between them is invisible
 * to every component.
 */

const hours = (n) => new Date(Date.now() + n * 3600_000).toISOString();

export const seed = {
  posts: [
    {
      id: 'seed-post-1',
      authorName: 'Alex Rivera',
      isAnonymous: false,
      title: 'Best resources for the Advanced Algorithms midterm?',
      content:
        'Looking for past-year question banks or summary slides on Graph Theory and DP. Happy to trade my project notes for them.',
      category: 'Academic',
      tag: 'CS Dept',
      upvotes: 24,
      comments: [
        { id: 'sc-1', authorName: 'Neha Iyer', content: 'Course drive, Unit 3 archive folder.', createdAt: '2h ago' },
      ],
      createdAt: '4h ago',
    },
    {
      id: 'seed-post-2',
      authorName: 'Anonymous Student',
      isAnonymous: true,
      title: 'Lost black WH-1000XM4 headphones, Central Library 2nd floor',
      content:
        'Left them on table 14 near the silent reading zone around 3 PM. Please reach out if they turned up at lost & found.',
      category: 'Lost & Found',
      tag: 'Library',
      upvotes: 41,
      comments: [
        {
          id: 'sc-2',
          authorName: 'Library Desk',
          content: 'A pair was deposited at 4:30 PM. Bring your student ID.',
          createdAt: '30m ago',
        },
      ],
      createdAt: '5h ago',
    },
    {
      id: 'seed-post-3',
      authorName: 'Meera Raghavan',
      isAnonymous: false,
      title: 'Mess menu poll: should Thursday dinner rotate weekly?',
      content:
        'Block C mess committee is collecting opinions before Friday. Drop a comment with your preference and hostel block.',
      category: 'General',
      tag: 'Block C',
      upvotes: 67,
      comments: [],
      createdAt: '7h ago',
    },
    {
      id: 'seed-post-4',
      authorName: 'Anonymous Student',
      isAnonymous: true,
      title: 'Genuinely struggling with placement season anxiety',
      content:
        'Everyone around me seems to have it figured out. If anyone else feels behind, you are not alone — and the counselling centre slot on Wednesdays actually helped me.',
      category: 'Confessions',
      tag: 'Anonymous',
      upvotes: 132,
      comments: [
        { id: 'sc-3', authorName: 'Anonymous Student', content: 'Needed to read this today. Thank you.', createdAt: '1h ago' },
      ],
      createdAt: '9h ago',
    },
    {
      id: 'seed-post-5',
      authorName: 'Rohit Kulkarni',
      isAnonymous: false,
      title: 'Free seat in the ECE study group — Fridays, 6 PM, Room 214',
      content: 'We work through the previous week problem set together. Open to any year, just show up.',
      category: 'Academic',
      tag: 'ECE Dept',
      upvotes: 29,
      comments: [],
      createdAt: '11h ago',
    },
  ],

  items: [
    {
      id: 'seed-item-1',
      sellerName: 'Alex Rivera',
      title: 'Engineering Mathematics (8th Ed) + formula chart',
      description: 'Mint condition, light pencil marks only. Comes with my handwritten formula summary sheets.',
      startingPrice: 400,
      currentBid: 650,
      highestBidderName: 'Priya S.',
      bidCount: 5,
      status: 'ACTIVE',
      expiresAt: 'In 3 hours',
      endsAt: hours(3),
      category: 'Books',
    },
    {
      id: 'seed-item-2',
      sellerName: 'Sarah Chen',
      title: 'Ergonomic mesh study chair, height adjustable',
      description: 'One semester of use. Genuinely comfortable for long sessions. Pickup from Block A.',
      startingPrice: 1200,
      currentBid: 1850,
      highestBidderName: 'Rohan M.',
      bidCount: 8,
      status: 'ACTIVE',
      expiresAt: 'In 6 hours',
      endsAt: hours(6),
      category: 'Furniture',
    },
    {
      id: 'seed-item-3',
      sellerName: 'Devika Nair',
      title: 'Casio FX-991EX scientific calculator',
      description: 'Exam-approved model. Battery replaced last month, original slip case included.',
      startingPrice: 600,
      currentBid: 780,
      highestBidderName: 'Imran Q.',
      bidCount: 3,
      status: 'ACTIVE',
      expiresAt: 'In 1 hour',
      endsAt: hours(1),
      category: 'Electronics',
    },
    {
      id: 'seed-item-4',
      sellerName: 'Karthik Menon',
      title: 'Hercules Roadeo cycle, recently serviced',
      description: 'Both tyres new, gears tuned last week. Selling because I am graduating.',
      startingPrice: 3000,
      currentBid: 4400,
      highestBidderName: 'Sana B.',
      bidCount: 12,
      status: 'ACTIVE',
      expiresAt: 'In 20 hours',
      endsAt: hours(20),
      category: 'Transport',
    },
  ],

  rides: [
    {
      id: 'seed-ride-1',
      driverName: 'Alex Rivera',
      origin: 'Main Campus Gate',
      destination: 'City Centre Metro',
      departureTime: 'Today, 5:30 PM',
      totalSeats: 4,
      availableSeats: 2,
      pricePerSeat: 80,
      passengers: ['Priya S.', 'David K.'],
    },
    {
      id: 'seed-ride-2',
      driverName: 'Sarah Chen',
      origin: 'North Hostel Complex',
      destination: 'Airport Terminal 2',
      departureTime: 'Tomorrow, 7:00 AM',
      totalSeats: 3,
      availableSeats: 1,
      pricePerSeat: 250,
      passengers: ['Kabir T.', 'Ananya P.'],
    },
    {
      id: 'seed-ride-3',
      driverName: 'Vikram Desai',
      origin: 'Block C Parking',
      destination: 'Railway Junction',
      departureTime: 'Friday, 4:15 PM',
      totalSeats: 4,
      availableSeats: 4,
      pricePerSeat: 120,
      passengers: [],
    },
  ],

  events: [
    {
      id: 'seed-event-1',
      title: 'Hackathon 2026 pitch night & mixer',
      description: 'Show an idea, find teammates, eat free pizza. No prior team required.',
      venue: 'Auditorium Hall B',
      dateTime: 'Friday, 6:00 PM',
      attendeesCount: 86,
      category: 'Tech',
    },
    {
      id: 'seed-event-2',
      title: 'Inter-hostel football final',
      description: 'Block B vs Block D. Bring your block colours.',
      venue: 'Main Ground',
      dateTime: 'Saturday, 4:30 PM',
      attendeesCount: 240,
      category: 'Sports',
    },
    {
      id: 'seed-event-3',
      title: 'Open mic & acoustic night',
      description: 'Fifteen slots, first come first served. Sign-up sheet in the comments.',
      venue: 'Amphitheatre',
      dateTime: 'Sunday, 7:00 PM',
      attendeesCount: 118,
      category: 'Culture',
    },
  ],

  deals: [
    {
      id: 'seed-deal-1',
      title: 'Flat 20% off all coffee & meal combos',
      businessName: 'Campus Bistro & Cafe',
      isPartner: true,
      discountPercent: 20,
      code: 'CAMPUS20',
      category: 'Food',
      distance: '0.2 km from Main Library',
      validUntil: 'Till end of month',
    },
    {
      id: 'seed-deal-2',
      title: 'Student rate: 15% off printing & binding',
      businessName: 'TechPrint Hub',
      isPartner: true,
      discountPercent: 15,
      code: 'PRINT15',
      category: 'Services',
      distance: 'Opposite Hostel Gate 2',
      validUntil: 'Every day',
    },
    {
      id: 'seed-deal-3',
      title: 'Buy one get one on filter coffee before 10 AM',
      businessName: 'Sunrise Tea Stall',
      isPartner: false,
      discountPercent: 50,
      code: 'EARLYBIRD',
      category: 'Food',
      distance: '400 m, near Gate 3',
      validUntil: 'Weekdays only',
    },
    {
      id: 'seed-deal-4',
      title: 'Half price on the first month of gym membership',
      businessName: 'Iron Yard Fitness',
      isPartner: true,
      discountPercent: 50,
      code: 'FRESHSTART',
      category: 'Fitness',
      distance: '1.1 km from North Gate',
      validUntil: 'New members only',
    },
  ],
};
